version: '3'

services:
  client:
    build:
      context: .
      dockerfile: jmeter-client.Dockerfile
      args:
        JVM_ARGS: "-Xms512m -Xmx1g -XX:+UseG1GC -XX:MaxMetaspaceSize=1g"
    container_name: jmeter-client
    hostname: jmeter-client
    tty: true
    ports:
      - "6000"
    volumes:
      - type: bind
        source: ./shared/testPlans
        target: /usr/share/testPlans
      - type: bind
        source: ./shared/rmi_keystore.jks
        target: /opt/apache-jmeter-5.6.3/bin/rmi_keystore.jks
    environment:
      - WORKERS=stress-testing-server-1,stress-testing-server-2,stress-testing-server-3
    networks:
      - jmeter-network
  server:
    build:
      context: .
      dockerfile: jmeter-server.Dockerfile
      args:
        JVM_ARGS: "-Xms512m -Xmx1g -XX:+UseG1GC -XX:MaxMetaspaceSize=512m -XX:+DisableExplicitGC"
    tty: true
    ports:
      - "1099"
      - "50000"
    volumes:
      - type: bind
        source: ./shared/rmi_keystore.jks
        target: /opt/apache-jmeter-5.6.3/bin/rmi_keystore.jks
    networks:
      - jmeter-network
  elasticsearch:
    image: elasticsearch:7.17.28
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - '9200:9200'
    networks:
      - jmeter-network
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - '3000:3000'
    networks:
      - jmeter-network
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis    
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - jmeter-network

networks:
  jmeter-network:
    driver: bridge
