{
 "title": "Bateria xx - Parceiro - xx/xx/xxxx",
 "time": { "from": "2023-04-03T03:36:28.530Z", "to": "2023-04-03T07:05:48.401Z" },
 "templating": {
  "list": [
   {
    "name": "cenarios",
    "label": "Filter by scenario",
    "query": "{\"find\": \"terms\", \"field\": \"SampleLabel.keyword\", \"query\": \"\"}"
   },
   {
    "name": "URL",
    "label": "Filter by URL",
    "query": "{\"find\": \"terms\", \"field\": \"URL.keyword\", \"query\": \"\"}"
   },
   {
    "name": "error",
    "label": "Only requests with errors",
    "query": "{\"find\": \"terms\", \"field\": \"ErrorCount\", \"query\": \"\"}"
   },
   {
    "name": "testidentifier",
    "label": "Test Identifier",
    "query": "{\"find\": \"terms\", \"field\": \"test.identifier.keyword\", \"query\": \"\"}"
   }
  ]
 },
 "panels": [
  { "title": "Users and Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Concurrent users per request",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:459",
       "fake": true,
       "field": "SampleLabel.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:460",
       "field": "SampleStartTime",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:457",
       "field": "GrpThreads",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SampleLabel:$cenarios && test.identifier:$testidentifier",
     "timeField": "SampleStartTime"
    },
    {
     "alias": "Concurrent users - All scenarios",
     "bucketAggs": [
      {
       "$$hashKey": "object:465",
       "field": "SampleStartTime",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:463",
       "field": "AllThreads",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SampleLabel:$cenarios && test.identifier:$testidentifier",
     "timeField": "SampleStartTime"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Throughput (RPM)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "targets": [
    {
     "alias": "Throughput",
     "bucketAggs": [
      {
       "$$hashKey": "object:691",
       "field": "SampleStartTime",
       "id": "2",
       "settings": { "interval": "60s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:689",
       "field": "SampleCount",
       "id": "1",
       "inlineScript": "_value",
       "meta": {},
       "settings": { "script": "_value" },
       "type": "sum"
      }
     ],
     "query": "ErrorCount:0 && SampleLabel:$cenarios && test.identifier:$testidentifier",
     "timeField": "SampleStartTime"
    },
    {
     "alias": "Concurrent users - All scenarios",
     "bucketAggs": [
      {
       "$$hashKey": "object:695",
       "field": "SampleStartTime",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:693",
       "field": "AllThreads",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SampleLabel:$cenarios && test.identifier:$testidentifier",
     "timeField": "SampleStartTime"
    }
   ]
  },
  {
   "title": "Throughput (RPM) per request",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:735",
       "fake": true,
       "field": "SampleLabel.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:736",
       "field": "SampleStartTime",
       "id": "2",
       "settings": { "interval": "60s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:733",
       "field": "SampleCount",
       "id": "1",
       "inlineScript": "_value",
       "meta": {},
       "settings": { "script": "_value" },
       "type": "sum"
      }
     ],
     "query": "URL.keyword:$URL && ErrorCount:0 && SampleLabel:$cenarios && test.identifier:$testidentifier",
     "timeField": "SampleStartTime"
    },
    {
     "alias": "Concurrent users - All scenarios",
     "bucketAggs": [
      {
       "$$hashKey": "object:741",
       "field": "SampleStartTime",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:739",
       "field": "AllThreads",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SampleLabel:$cenarios && test.identifier:$testidentifier",
     "timeField": "SampleStartTime"
    }
   ]
  },
  { "title": "Response time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Average response time (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "alias": "Average Response Time ",
     "bucketAggs": [
      {
       "field": "test.identifier.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:796",
       "field": "SampleStartTime",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:793",
       "field": "ResponseTime",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios && test.identifier:$testidentifier",
     "timeField": "SampleStartTime"
    },
    {
     "alias": "Concurrent users - All scenarios",
     "bucketAggs": [
      {
       "$$hashKey": "object:801",
       "field": "SampleStartTime",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:799",
       "field": "AllThreads",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SampleLabel:$cenarios && test.identifier:$testidentifier",
     "timeField": "SampleStartTime"
    }
   ]
  },
  {
   "title": "Average response time per request (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "alias": "Average Response Time {{SampleLabel.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:795",
       "fake": true,
       "field": "SampleLabel.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:796",
       "field": "SampleStartTime",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:793",
       "field": "ResponseTime",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios && test.identifier:$testidentifier",
     "timeField": "SampleStartTime"
    },
    {
     "alias": "Concurrent users - All scenarios",
     "bucketAggs": [
      {
       "$$hashKey": "object:801",
       "field": "SampleStartTime",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:799",
       "field": "AllThreads",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SampleLabel:$cenarios && test.identifier:$testidentifier",
     "timeField": "SampleStartTime"
    },
    {
     "alias": "Global average response time",
     "bucketAggs": [
      {
       "$$hashKey": "object:805",
       "field": "SampleStartTime",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:803",
       "field": "ResponseTime",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "identifier.keyword:$TEST_IDENTIFIER",
     "timeField": "SampleStartTime"
    }
   ]
  },
  {
   "title": "Top 10 - Average response time per request (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "alias": "Average response time {{URL.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:895",
       "fake": true,
       "field": "URL.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:896",
       "fake": true,
       "field": "SampleStartTime",
       "id": "4",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:893",
       "field": "ResponseTime",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios && test.identifier:$testidentifier",
     "timeField": "SampleStartTime"
    },
    {
     "alias": "Concurrent users - All scenarios",
     "bucketAggs": [
      {
       "$$hashKey": "object:901",
       "field": "SampleStartTime",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:899",
       "field": "AllThreads",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios && test.identifier:$testidentifier",
     "timeField": "SampleStartTime"
    }
   ]
  },
  {
   "title": "Heatmap - Average response time (milliseconds) per scenario",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:969",
       "fake": true,
       "field": "SampleLabel.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:970",
       "field": "SampleStartTime",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:967",
       "field": "ResponseTime",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios && test.identifier:$testidentifier",
     "timeField": "SampleStartTime"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data received per request",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "alias": "Data received - All scenarios",
       "bucketAggs": [
        {
         "$$hashKey": "object:1007",
         "field": "SampleStartTime",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1005",
         "field": "Bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios && test.identifier:$testidentifier",
       "timeField": "SampleStartTime"
      },
      {
       "alias": "Received {{SampleLabel.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1011",
         "fake": true,
         "field": "SampleLabel.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1012",
         "field": "SampleStartTime",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1009",
         "field": "Bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios && test.identifier:$testidentifier",
       "timeField": "SampleStartTime"
      },
      {
       "alias": "Concurrent users - All scenarios",
       "bucketAggs": [
        {
         "$$hashKey": "object:1017",
         "field": "SampleStartTime",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1015",
         "field": "AllThreads",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios && test.identifier:$testidentifier",
       "timeField": "SampleStartTime"
      }
     ]
    },
    {
     "title": "Data sent per request",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "alias": "Data sent - All scenarios",
       "bucketAggs": [
        {
         "$$hashKey": "object:1081",
         "field": "SampleStartTime",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1079",
         "field": "SentBytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios && test.identifier:$testidentifier",
       "timeField": "SampleStartTime"
      },
      {
       "alias": "Sent {{SampleLabel.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1085",
         "fake": true,
         "field": "SampleLabel.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1086",
         "field": "SampleStartTime",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1083",
         "field": "SentBytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios && test.identifier:$testidentifier",
       "timeField": "SampleStartTime"
      },
      {
       "alias": "Concurrent users - All scenarios",
       "bucketAggs": [
        {
         "$$hashKey": "object:1091",
         "field": "SampleStartTime",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1089",
         "field": "AllThreads",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios && test.identifier:$testidentifier",
       "timeField": "SampleStartTime"
      }
     ]
    }
   ]
  },
  { "title": "Errors and Response codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Percentage of errors per request",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "test.identifier.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "SampleStartTime", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ErrorCount",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios",
     "timeField": "SampleStartTime"
    },
    {
     "alias": "Concurrent users - All scenarios",
     "bucketAggs": [
      { "field": "SampleStartTime", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "AllThreads",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios",
     "timeField": "SampleStartTime"
    }
   ]
  },
  {
   "title": "Number of errors per response code",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "alias": "HTTP Response: {{ResponseCode.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:1151",
       "fake": true,
       "field": "ResponseCode.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1152",
       "field": "SampleStartTime",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1149", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios",
     "timeField": "SampleStartTime"
    },
    {
     "alias": "Concurrent users - All scenarios",
     "bucketAggs": [
      {
       "$$hashKey": "object:1157",
       "field": "SampleStartTime",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1155",
       "field": "AllThreads",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios",
     "timeField": "SampleStartTime"
    }
   ]
  },
  {
   "title": "Percentage of errors per request",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "SampleLabel.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "SampleStartTime", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ErrorCount",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios",
     "timeField": "SampleStartTime"
    },
    {
     "alias": "Concurrent users - All scenarios",
     "bucketAggs": [
      { "field": "SampleStartTime", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "AllThreads",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios",
     "timeField": "SampleStartTime"
    }
   ]
  },
  {
   "title": "Number of HTTP errors per scenario",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "alias": "{{SampleLabel.keyword}} Tottal HTTP errors",
     "bucketAggs": [
      {
       "fake": true,
       "field": "SampleLabel.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "SampleStartTime", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ErrorCount",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "ResponseCode.keyword: [400 TO 599] && URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios",
     "timeField": "SampleStartTime"
    },
    {
     "alias": "Concurrent users - All scenarios",
     "bucketAggs": [
      { "field": "SampleStartTime", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "AllThreads",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios",
     "timeField": "SampleStartTime"
    }
   ]
  },
  {
   "title": "Number of assertion errors per type",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "alias": "Concurrent users - All scenarios",
     "bucketAggs": [
      { "field": "SampleStartTime", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "AllThreads",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios",
     "timeField": "SampleStartTime"
    },
    {
     "alias": "Assertion {{AssertionResults.failureMessage.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "AssertionResults.failureMessage.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "SampleStartTime", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "SampleStartTime"
    }
   ]
  },
  {
   "title": "Number of assertion and HTTP errors X Total number of requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "AssertionResults.failureMessage.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "SampleStartTime", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Success",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "SampleStartTime"
    },
    {
     "alias": "Total Requests - All scenarios",
     "bucketAggs": [
      { "field": "SampleStartTime", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "AllThreads",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios",
     "timeField": "SampleStartTime"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "ResponseCode.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "SampleStartTime", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "ResponseCode.keyword: [400 TO 599] && URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios",
     "timeField": "SampleStartTime"
    }
   ]
  },
  {
   "title": "Response codes per request",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1195",
       "fake": true,
       "field": "SampleLabel.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1196",
       "fake": true,
       "field": "URL.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1197",
       "field": "ResponseCode.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1193", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "URL.keyword:$URL && ErrorCount:$error && SampleLabel:$cenarios && test.identifier:$testidentifier",
     "timeField": "SampleStartTime"
    }
   ]
  }
 ]
}